name: Build and Test Java Application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Compile Java Application
        run: |
          javac -d ./bin src/App.java
          java -cp ./bin org.junit.platform.console.ConsoleLauncher --scan-classpath --class-path ./bin --reports-dir=test-results
